bbs---master/bbs/apps/cms/__init__.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from .views import bp
import  apps.cms.hook

bbs---master/bbs/apps/cms/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from flask import Blueprint, render_template, views, request, session, redirect, url_for, g, jsonify
from .forms import LoginForm, ResetForm, ResetEmailForm, AddBoardForm, UpdateBoardForm
from .modles import CmsUser, CMSPermission
from .decorate import login_required, permission_required
from utils import restful, zlcache
from exts import mail
from flask_mail import Message
from exts import db
from apps.modles import BoardModel, HighlightPostModel, PostModel
import config
import string, random
from tasks import send_mail

# todo 这个以后要做到发送邮箱需要记录在日志里，方便查看，要记录下来给哪些人发送了新的邮件。
# todo  在进行flask分页的时候 还是使用现成的flask-page...，跟bootstrap结合出来的

# todo 记录访问系统的日志，访问bbs论坛的哪个地方，ip是多少，时间是多少，这样才能够更好的维护和安全

bp = Blueprint('cms', __name__, url_prefix='/cms')


@bp.route('/')
@login_required
def index():
    return "cms index"


# 个人中心页面
@bp.route('/probfile/')
@login_required
def probfile():
    return render_template('cms/cms_probfile.html')


# 添加加精帖子视图函数
@bp.route('/hpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def hpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    highlight = HighlightPostModel()
    highlight.post = post

    db.session.add(highlight)
    db.session.commit()
    return restful.success()


# 取消加精帖子视图函数
@bp.route('/uhpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def uhpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()


# 移除加精帖子视图函数
@bp.route('/dpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def dpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    db.session.delete(post)
    db.session.commit()
    return restful.success()


# 帖子管理模块视图
@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html', posts=post_list)


# 发送邮箱验证码接口
@bp.route('/send_mail/')
def sendmail_captcha():
    email = request.args.get('email')
    if not email:
        return restful.params_error('请传递邮箱参数！')
    captcha = list(string.ascii_letters)
    # 获得a-zA-Z的字符串 列表
    captcha_num = map(lambda x: str(x), range(0, 10))
    # 获得0-9的数字 的列表
    captcha.extend(captcha_num)
    # 列表的一个方法，使得列表之间能够继承
    # print("".join(captcha))
    # 结合完毕，剩下就是随机打印出6个不同的字符串和数字了
    result_captcha = random.sample(captcha, 6)
    result_captcha = "".join(result_captcha)
    print(result_captcha)
    message = Message("bbs论坛验证码", recipients=[email],
                      body="关于您更改默认邮箱，我们向您发送了一条邮箱验证码，邮箱验证码为%s ，如果不是本人操作，请自觉忽略" % result_captcha)
    try:
        send_mail.delay('知了论坛邮箱验证码', recipients=[email], body='你的验证码是：%s' % captcha)
    except:
        return restful.server_error()

    zlcache.set(email, captcha)  # 添加验证码缓存
    return restful.success()


# 注销页面
@bp.route('/logout/')
@login_required
def logout():
    session.clear()
    return redirect(url_for('cms.login'))


# 评论管理
@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


# 板块管理
@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models = BoardModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)


# 添加板块视图
@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data

        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


# 更新板块视图，就是编辑的地方
@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块！')
    else:
        return restful.params_error(message=form.get_error())


# 删除板块视图
@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.params_error('请输入板块id!')

    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块！')

    db.session.delete(board)
    db.session.commit()
    return restful.success()


# 前台用户管理
@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


# cms用户管理
@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.COMUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


# cms组管理
@bp.route('/groles/')
@login_required
@permission_required(CMSPermission.COMUSER)
def groles():
    return render_template('cms/cms_groles.html')


# 登录类视图
class LoginView(views.MethodView):
    def get(self, message=None):
        return render_template('cms/cms_layui_login.html', message=message)

    # message在获取之后，再次调用message方法，如果重新渲染的没有message的值，那么传入message的值也没用了

    def post(self):
        form = LoginForm(request.form)
        print(form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.email.data
            user = CmsUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                session.permanent = True
                # 这个加入session之后就是正好31天，一个月
                return redirect(url_for('cms.probfile'))
            else:
                return self.get(message='用户名或者密码错误')
        else:
            print(form.errors)
            self.get(message='表单验证错误')
        return self.get(message='用户名或者密码错误')


# 修改密码功能
class ResetView(views.MethodView):
    decorators = [login_required, permission_required(CMSPermission.VICTIOR)]  # 保证用户登陆

    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetForm(request.form)  # 验证修改密码
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user  # 使用g对象传递用户对象
            if user.check_password(oldpwd):
                # 更新数据库中的密码
                user.password = newpwd
                db.session.commit()
                # 返回json数据
                # return jsonify({"code": 200, "message": ""})
                return restful.success()
            else:
                # return jsonify({"code": 400, "message": "旧密码输入错误"})
                return restful.params_error("旧密码错误")
        else:
            message = form.get_error()  # 使用父类的get_error()方法获取错误信息
            # return jsonify({"code": 400, "message": message})
            return restful.params_error(message)


# 修改邮箱
class ResetEmailView(views.MethodView):
    decorators = [login_required, permission_required(CMSPermission.VICTIOR)]

    # 装饰器都是要加decorators的，不加s会报错
    def get(self):
        return render_template('cms/cms_resetmail.html')

    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            user = g.cms_user
            # 要先从g.cms_user中获取到user 才能够进行修改的
            user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())


bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))
bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/', view_func=ResetView.as_view('resetpwd'))

bbs---master/bbs/apps/front/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from flask import Blueprint, views, render_template, make_response, request, session, url_for, g, abort
from utils.captcha import Captcha
from utils import zlcache, restful, safeutils
from io import BytesIO
from .forms import SignupForm, SigninForm, AddPostForm,AddCommentForm
from .models import FrontUser
from exts import db
from .decorate import login_required
import config
from flask_paginate import Pagination, get_page_parameter
from apps.modles import BoardModel, PostModel,CommentModel,HighlightPostModel
from sqlalchemy.sql import  func

bp = Blueprint('front', __name__)


#todo  学习celery 异步机制
#todo  celery的异步机制 celery-A tasks.celery --pool=eventlet worker --loglevel=info 这样就可以执行了

# bbs论坛前台页面，找个页面还是挺不错的，可以学习到很多的东西，不过这个和我之前做的差不太多吧
# todo 帖子管理，用户登录
@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)  # 排序因子
    # banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)  # 降序
    boards = BoardModel.query.all()  # 板块
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    if sort == 1:
        #     # 默认按照创建时间倒序排列
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精时间倒序排列
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞数量倒序排序 由于还没有添加点赞功能，暂时按照默认排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论数量倒序排列
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:  # 特定板块的帖子
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:  # 全部帖子
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0,
                            inner_window=2)  # 分页器
    context = {  # 上下文
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort,
    }
    return render_template('front/front_index.html', **context)


# 帖子详情视图函数
@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)

# 添加评论视图函数
@bp.route('/acomment/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这篇帖子！')
    else:
        return restful.params_error(form.get_error())


# 验证码视图函数，这个函数要进行保存图片，其中的验证码是根据4位数字，生成一个验证码的图片，注意是一个图片，这个图片比较特殊，我们可以用其他的来解决
@bp.route('/captcha/')
def graph_captcha():
    captcha, image = Captcha.gene_graph_captcha()
    print('图形验证码是：', captcha)  # 打印出图形验证码
    zlcache.set(captcha.lower(), captcha.lower())  # 把验证码添加到memcached缓存中
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


# 添加帖子视图
@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data

            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')

            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user  # 传递前台用户
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


# 写一个前端真的是费劲啊，我真是希望有个好的前端。
class SignupView(views.MethodView):
    def get(self):
        # 跳转到之前的页面,如果存在的话
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        # 验证表单
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data

            # 创建新的前台用户
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())  # 打印出错误信息
            return restful.params_error(message=form.get_error())


# 前台登录类视图
class SigninView(views.MethodView):
    def get(self):
        # 跳转到之前的页面，如果有的话
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        # 验证登录
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            user = FrontUser.query.filter_by(telephone=telephone).first()
            print(password)
            print(user.check_password(password))
            print(user)
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号码或密码错误！')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

bbs---master/bbs/templates/cms/cms_admin.html
{  # {% extends 'cms/cms_base.html' %}#}

{% block title %}
后台管理页面
{% endblock %}

bbs---master/bbs/templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macors.html' import static %}
{% block title %}
    轮播图管理
{% endblock %}

{% block css_style %}
    <style>
        .top-box button {
            float: right;
        }
    </style>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>

    <script src="{{ static('common/zlqiniu.js') }}"></script>
    <script src="{{ static('cms/js/banners.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <td>名称</td>
            <td>图片链接</td>

            <td>跳转链接</td>
            <td>优先级</td>
            <td>创建日期</td>
            <td>操作</td>
        </tr>
        </thead>

        <tbody>
        {% for banner in banners %}
            <tr data-name="{{ banner.name }}" data-id="{{ banner.id }}" data-img="{{ banner.img_url }}"
                data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}">

                <td>{{ banner.name }}</td>
                <td><a href="{{ banner.img_url }}" target="_blank">{{ banner.img_url }}</a></td>
                <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                <td>{{ banner.priority }}</td>
                <td>{{ banner.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <!-- Modal -->
    <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">轮播图</h4>
                </div>
                <div class="modal-body">
                    <form action="" class="form-horizontal">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">名称</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">图片</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="img_url" placeholder="轮播图图片">
                            </div>
                            <button class="col-sm-2 btn btn-info" id="upload-btn">添加图片</button>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">跳转</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">权重</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="priority" placeholder="权重">
                            </div>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="save_banner_btn">保存</button>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

bbs---master/bbs/templates/cms/cms_base.html
{% from "common/_macors.html" import static %}
{#laui模板使用着就是不一样啊#}
{#引入宏#}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{{ static('layui/css/layui.css') }}">
    {% include 'common/_heads.html' %}
    <title>{% block title %}{% endblock %}</title>

    <script src="{{ static('js/cms_base.js') }}"></script>
    {% block css_style %}
    {% endblock %}



</head>


<body class="layui-layout-body">
{% set cms_user = g.cms_user %}
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">trigo安全论坛</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item"><a href="">控制台</a></li>
            <li class="layui-nav-item"><a href="">商品管理</a></li>
            <li class="layui-nav-item"><a href="">用户</a></li>
            <li class="layui-nav-item">
                <a href="javascript:;">其它系统</a>
                <dl class="layui-nav-child">
                    <dd><a href="">邮件管理</a></dd>
                    <dd><a href="">消息管理</a></dd>
                    <dd><a href="">授权管理</a></dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="{{ url_for('cms.probfile') }}">
                    <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
                    {{ g.cms_user.username }}
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="">基本资料</a></dd>
                    <dd><a href="">安全设置</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item"><a href="{{ url_for('cms.logout') }}">注销</a></li>
        </ul>
    </div>
    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item">
                    <a class="" href="#s">首页</a>
                </li>
                <li class="layui-nav-item">
                    <a class="" href="{{ url_for('cms.probfile') }}">个人信息</a>
                </li>
                <li class="layui-nav-item">
                    <a class="" href="{{ url_for('cms.resetpwd') }}">修改密码</a>
                </li>
                <li class="layui-nav-item"><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>

                {% if cms_user.has_permissions(CMSPermission.POSTER) %}
                    <li class="layui-nav-item"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}
                {% if cms_user.has_permissions(CMSPermission.COMMENTER) %}
                    <li class="layui-nav-item"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                {% endif %}
                {% if cms_user.has_permissions(CMSPermission.BOARDER) %}
                    <li class="layui-nav-item"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}
                {% if cms_user.has_permissions(CMSPermission.FRONTUSER) %}
                    <li class="layui-nav-item"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                {% endif %}
                {% if cms_user.has_permissions(CMSPermission.COMUSER) %}
                    <li class="layui-nav-item"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                    <li class="layui-nav-item"><a href="{{ url_for('cms.groles') }}">CMS组管理</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <div class="layui-footer">
        <!-- 底部固定区域 -->
        © layui.com - 底部固定区域
    </div>
</div>
<script src="{{ static('layui/layui.js') }}"></script>
<script>
    //JavaScript代码区域
    layui.use('element', function () {
        var element = layui.element;

    });
</script>
</body>
</html>

bbs---master/bbs/templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macors.html' import static %}

{% block title %}板块管理{% endblock %}

{% block css_style %}
    <script src="{{ static('cms/js/cms_boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float: right;" id="add-board-btn">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>0</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

bbs---master/bbs/templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}
{% block title %}
这是评论管理
{% endblock %}
{% block css_style %}
{% endblock %}
{% block content %}
    {{ self.title() }}
{% endblock %}

bbs---master/bbs/templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}
{% block title %}
这是CMS用户管理
{% endblock %}
{% block css_style %}
{% endblock %}
{% block content %}
    {{ self.title() }}
{% endblock %}

bbs---master/bbs/templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}
{% block title %}
这是前台用户管理
{% endblock %}
{% block css_style %}
{% endblock %}
{% block content %}
    {{ self.title() }}
{% endblock %}

bbs---master/bbs/templates/cms/cms_groles.html
{% extends 'cms/cms_base.html' %}
{% block title %}
这是CMS组管理
{% endblock %}
{% block css_style %}
{% endblock %}
{% block content %}
    {{ self.title() }}
{% endblock %}

bbs---master/bbs/templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macors.html' import static %}

{% block title %}帖子管理{% endblock %}

{% block css_style %}
    <script src="{{ static('cms/js/cms_posts.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>发布时间</th>
            <th>板块</th>
            <th>作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                <td><a target="_blank" href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                </td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.board.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if post.highlight %}
                        <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                    {% else %}
                        <button class="btn btn-default btn-xs highlight-btn">加精</button>
                    {% endif %}
                    <button class="btn btn-danger btn-xs delete-post-btn">移除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}