bbs---master/bbs/apps/front/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"

from exts import db
import shortuuid, enum
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4

# 前台用户类，这个类可以是创建前台对象
class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)  # 使用shortuuid.uuid生成id
    telephone = db.Column(db.String(11), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)  # 密码比较特殊，需要加密
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(FrontUser, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        return check_password_hash(self._password, rawpwd)

bbs---master/bbs/apps/front/forms.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from wtforms import  StringField,IntegerField
from wtforms.validators import Length, InputRequired, Email, EqualTo,Regexp
from wtforms import  ValidationError
from utils import zlcache
from apps.forms import BaseForm

class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1", message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的图形验证码！')])

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        graph_captcha_mem = zlcache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证码错误！')

# 前台登录表单验证类
class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remember = StringField()

# 添加帖子表单验证类
class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])


# 添加评论验证表单
class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id!')])

bbs---master/bbs/apps/front/__init__.py
#!/usr/bin/env python
#-*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from .views import bp
from . import  hooks

bbs---master/bbs/apps/front/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Author  : "你们的饭不好吃"
from flask import Blueprint, views, render_template, make_response, request, session, url_for, g, abort
from utils.captcha import Captcha
from utils import zlcache, restful, safeutils
from io import BytesIO
from .forms import SignupForm, SigninForm, AddPostForm,AddCommentForm
from .models import FrontUser
from exts import db
from .decorate import login_required
import config
from flask_paginate import Pagination, get_page_parameter
from apps.modles import BoardModel, PostModel,CommentModel,HighlightPostModel
from sqlalchemy.sql import  func

bp = Blueprint('front', __name__)


#todo  学习celery 异步机制
#todo  celery的异步机制 celery-A tasks.celery --pool=eventlet worker --loglevel=info 这样就可以执行了

# bbs论坛前台页面，找个页面还是挺不错的，可以学习到很多的东西，不过这个和我之前做的差不太多吧
# todo 帖子管理，用户登录
@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)  # 排序因子
    # banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)  # 降序
    boards = BoardModel.query.all()  # 板块
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    if sort == 1:
        #     # 默认按照创建时间倒序排列
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精时间倒序排列
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞数量倒序排序 由于还没有添加点赞功能，暂时按照默认排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论数量倒序排列
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:  # 特定板块的帖子
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:  # 全部帖子
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0,
                            inner_window=2)  # 分页器
    context = {  # 上下文
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort,
    }
    return render_template('front/front_index.html', **context)


# 帖子详情视图函数
@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)

# 添加评论视图函数
@bp.route('/acomment/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这篇帖子！')
    else:
        return restful.params_error(form.get_error())


# 验证码视图函数，这个函数要进行保存图片，其中的验证码是根据4位数字，生成一个验证码的图片，注意是一个图片，这个图片比较特殊，我们可以用其他的来解决
@bp.route('/captcha/')
def graph_captcha():
    captcha, image = Captcha.gene_graph_captcha()
    print('图形验证码是：', captcha)  # 打印出图形验证码
    zlcache.set(captcha.lower(), captcha.lower())  # 把验证码添加到memcached缓存中
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


# 添加帖子视图
@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data

            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')

            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user  # 传递前台用户
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


# 写一个前端真的是费劲啊，我真是希望有个好的前端。
class SignupView(views.MethodView):
    def get(self):
        # 跳转到之前的页面,如果存在的话
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        # 验证表单
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data

            # 创建新的前台用户
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())  # 打印出错误信息
            return restful.params_error(message=form.get_error())


# 前台登录类视图
class SigninView(views.MethodView):
    def get(self):
        # 跳转到之前的页面，如果有的话
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        # 验证登录
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            user = FrontUser.query.filter_by(telephone=telephone).first()
            print(password)
            print(user.check_password(password))
            print(user)
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号码或密码错误！')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

bbs---master/bbs/templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了课堂404页面</title>
</head>
<body>
您要找到页面已经到火星去了～～
<div>
    <a href="/">回到首页</a>
</div>
</body>
</html>

bbs---master/bbs/templates/front/front_apost.html
{% extends 'front/front_base.html' %}
{% from 'common/_macors.html' import static %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
    <form action="" method="post">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" class="form-control" name="title">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">板块</span>
                <select name="board_id" id="" class="form-control">
                    {% for board in boards %}
                        <option value="{{ board.id }}">{{ board.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <script id="editor" type="text/plain"></script>
        </div>
        <div class="form-group">
            <button class="btn btn-danger" id="submit-btn">发布帖子</button>
        </div>
    </form>
{% endblock %}

bbs---master/bbs/templates/front/front_base.html
{% from "common/_macors.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include "common/front_heads.html" %}
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
{# 导航条 #}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">知了课堂Python论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            {# 用户设置下拉列表 #}
            <ul class="nav navbar-nav navbar-right">
                {% if g.front_user %}
                    <span id="login-tag" data-is-login="1" style="display: none;"></span>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            {{ g.front_user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="#">个人中心</a></li>
                            <li><a href="#">设置</a></li>
                            <li><a href="#">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="main-container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

bbs---master/bbs/templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macors.html" import static %}

{% block title %}知了课堂Python论坛{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
{% endblock %}


{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
{#                        指示器#}
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="https://www.xfz.cn/explore/xfz2019/?adf=top.banner">
                        <img src="https://static-image.xfz.cn/1571292192_9.jpg" alt="...">
                    </a>
                    <div class="carousel-caption">
                        ...
                    </div>
                </div>
                <div class="item">
                    <a href="https://mp.weixin.qq.com/s/FsKLVY-0MGC0tDV7JsVrYQ?adf=top.banner">
                        <img src="https://static-image.xfz.cn/1571885973_544.jpg" alt="...">
                    </a>
                    <div class="carousel-caption">
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

                    <div class="post-group">
                        <ul class="post-group-head">
                            {% if current_sort == 1 %}
                                <li class="active"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                            {% else %}
                                <li><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                            {% endif %}
                            {% if current_sort == 2 %}
                                <li class="active"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                            {% else %}
                                <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                            {% endif %}
                            {% if current_sort == 3 %}
                                <li class="active"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                            {% else %}
                                <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                            {% endif %}
                            {% if current_sort == 4 %}
                                <li class="active"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                            {% else %}
                                <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                            {% endif %}
                        </ul>
                        <ul class="post-list-group">
                            {% for post in posts %}
                                <li>
                                    <div class="author-avatar-group">
                                        <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}"
                                             alt="">
                                    </div>
                                    <div class="post-info-group">
                                        <p class="post-title">
                                            <a href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a>
                                            {% if post.highlight %}
                                                <span class="label label-danger">精华帖</span>
                                            {% endif %}
                                        </p>
                                        <p class="post-info">
                                            <span>作者:{{ post.author.username }}</span>
                                            <span>发表时间:{{ post.create_time }}</span>
                                            <span>评论:0</span>
                                            <span>阅读:0</span>
                                        </p>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                        <div style="text-align:center;">
                        {{ pagination.links }}
                        </div>
                    </div>
    </div>
    <div class="sm-container">
        <div style="padding-bottom:10px;">
                        <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
            {% for board in boards %}
                {% if board.id == current_board %}
                    <a href="{{ url_for("front.index",bd=board.id) }}"
                       class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

bbs---master/bbs/templates/front/front_pdetail.html
{% extends 'front/front_base.html' %}
{% from 'common/_macors.html' import static %}
{#加一个safe 是相信这个代码不会产生xss攻击#}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_pdetail.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_pdetail.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间：{{ post.create_time }}</span>
                <span>作者：{{ post.author.username }}</span>
                <span>所属板块：{{ post.board.name }}</span>
                <span>阅读数：{{ post.read_count }}</span>
                <span>评论数：0</span>
            </p>
            <article class="post-content" id="post-content" data-id="{{ post.id }}">
                {{ post.content|safe }}
            </article>
        </div>
        <div class="comment-group">
            <h3>评论列表</h3>
            <ul class="comment-list-group">
                {% for comment in post.comments %}
                    <li>
                        <div class="avatar-group">
                            <img src="{{ comment.author.avatar or static('common/images/logo.png') }}" alt="">
                        </div>
                        <div class="comment-content">
                            <p class="author-info">
                                <span>{{ comment.author.username }}</span>
                                <span>{{ comment.create_time }}</span>
                            </p>
                            <p class="comment-txt">
                                {{ comment.content|safe }}
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="add-comment-group">
            <script id="editor" type="text/plain"></script>
            <div class="comment-btn-group">
                <button class="btn btn-primary" id="comment-btn">发表评论</button>
            </div>
        </div>
    </div>
    <div class="sm-container"></div>
{% endblock %}

bbs---master/bbs/templates/front/front_signbase.html
{% from 'common/_macors.html' import static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>
    <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">
    <script src="{{ static("common/sweetalert/sweetalert.min.js") }}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js") }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css') }}">
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="{{ static('common/images/logo.png') }}" alt="">
            </a>
        </div>
        <h2 class="page-title">
            {% block h2_block %}{% endblock %}
        </h2>
        <div class="sign-box">
            {% block signbox %}{% endblock %}
        </div>
    </div>
</body>
</html>

bbs---master/bbs/templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macors.html' import static %}

{% block title %}
    知了课堂登录页面
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signin.js') }}"></script>
{% endblock %}

{% block h2_block %}
    知了课堂账号登录
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码" >
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住我
        </label>
    </div>
    <div class="form-group">
        <button id="submit-btn" class="btn btn-warning btn-block">立即登录</button>
    </div>
    <div class="form-group">
        <a href="{{ url_for('front.signup') }}" class="sign-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link" style="float: right;">找回密码</a>
    </div>
{% endblock %}

bbs---master/bbs/templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macors.html' import static%}

{% block title %}
    知了课堂注册
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}

{% block h2_block %}
    知了课堂账号注册
{% endblock %}

{% block signbox %}
    <div class="form-group">
            <input type="text" class="form-control" name="telephone" placeholder="手机号码" style="background-color: rgba(0,0,0,0);color: white">
{#            <span class="input-group-btn">#}
{#                <button id="sms-captcha-btn" class="btn btn-default" style="background-color: rgba(255,255,255,0.9);color: black">发送验证码</button>#}
{#            </span>#}
    </div>
{#    短信验证码，因为这个阿里云平台没有调试好，就算了吧#}
{#    <div class="form-group">#}
{#        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码" style="background-color: rgba(0,0,0,0.2);color: white">#}
{#    </div>#}
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名" style="background-color: rgba(0,0,0,0.2);color: white">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码" style="background-color: rgba(0,0,0,0.2);color: white">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码" style="background-color: rgba(0,0,0,0.2);color: white">
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码" style="background-color: rgba(0,0,0,0.2);color: white">
            <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="" style="background-color: rgba(0,0,0,0.2);color: white">
            </span>
        </div>
    </div>
    <div class="form-group">
           <span style="display:none;" id="return-to-span">{{ return_to }}</span>
        <button class="btn btn-warning btn-block" id="submit-btn" style="background-color:rgba(255,255,255,0.8); color: black;border: 0px">立即注册</button>
    </div>
{% endblock %}